adding task 20_2
a-kotova/new_test pull request #2
Opened 2020-11-30 13:54 UTC by a-kotova

2020-11-30 13:59 UTC, s34rching requested changes
Запустил 20 раз - все зеленое.
Посмотри на комментарии и реши, что ты хочешь переделать.

2020-11-30 13:59 UTC, s34rching commented on cypress/integration/page-objects/GoogleCart.js
> +    get itemsQty () {
не слишком длинное имя, можно не сокращать Qty

2020-11-30 13:59 UTC, s34rching commented on cypress/integration/page-objects/GoogleCart.js
> +        let prices = array.map(product => product.price*product.cart_qty);
`product.price * product.cart_qty` - оставляй место вокруг опреатора, сложно читать

2020-11-30 13:59 UTC, s34rching commented on cypress.json
> +    "cartReloadTimeout": 5000
отлично, что используешь `env`, но идея этой переменной не лучшая

2020-11-30 13:59 UTC, s34rching commented on cypress/fixtures/singleColorProducts.json
> +    "url": "/product/plate_for_thermostat_e"
Свойства, которые не используются, хранить не надо.

Оставь только нужные.

2020-11-30 13:59 UTC, s34rching commented on cypress/integration/page-objects/GoogleCart.js
> +        total = +total.toFixed(2)
выглядит странно, попробуй лучше с parseFloat

2020-11-30 13:59 UTC, s34rching commented on cypress/integration/tests/20_2_test.js
> +            cy.log("WHEN user changes product's quantity" )
Здесь начинается уже совершенно другой тест.
Не пытайся вложить все проверки в один тест.

Идея такая:
- Либо тебе не нужно проверять, что `total` до изменения числа товаров в корзине правильный, так как эта проверка не имеет никакого значения здесь, так как тебе нужно проверить, что после изменения количества товаров в корзине новый `total` правильный.

- Если ее все-таки нужно сделать, то нужно сделать это двумя тестами, потому что если проверка начального `total` упадет, то ты не сможешь проверить, что произойдет при изменении количества товаров. Здесь нет никакого отличия от ручного тестирования и трека кейсов при прохождении: тест будет делать слишком много и ты не сможешь на него сослаться при появляении дефекта.

2020-11-30 13:59 UTC, s34rching commented on cypress/integration/tests/20_2_test.js
> +    before(() => {
я не вижу особого смысла делать здесь хук (`before`, `beforeEach`, `after`, `afterEach` - это хуки), потому что это не предварительные шаги в контексте этого файла, а просто шаги

2020-11-30 13:59 UTC, s34rching commented on cypress/integration/tests/20_2_test.js
> +                Cart.getItemByUrl(product.url).should('exist')
я понимаю, что это Катя создавала этот таск, поэтому этот пункт только для рассмотрения:

когда ты используешь `Page Object Pattern`, то зачастую названия методов, используемых в тестах, настолько однозначны, что не нужно никаких пояснений и логирований для того, чтобы понять, что выполняется.

Просто имей ввиду.

2020-11-30 13:59 UTC, s34rching commented on cypress/integration/tests/20_2_test.js
> +                Cart.getItemByUrl(product.url).should('exist')
И, если есть возможность не использовать проверки `should` в рамках хуков, не надо их использовать - не замедляй тесты.

2020-11-30 13:59 UTC, s34rching commented on cypress/integration/tests/20_2_test.js
> +            this.products.forEach((product, index) => {
this?

2020-11-30 14:04 UTC, s34rching requested changes
Again

2020-11-30 14:50 UTC, a-kotova commented on cypress/integration/page-objects/GoogleCart.js
> +    get itemsQty () {
исправила на itemsQuantity

2020-11-30 14:52 UTC, a-kotova commented on cypress/integration/page-objects/GoogleCart.js
> +        let prices = array.map(product => product.price*product.cart_qty);
исправила

2020-11-30 14:53 UTC, a-kotova commented on cypress/fixtures/singleColorProducts.json
> +    "url": "/product/plate_for_thermostat_e"
исправила

2020-11-30 16:42 UTC, a-kotova commented on cypress/integration/page-objects/GoogleCart.js
> +        total = +total.toFixed(2)
исправила на math.round

2020-11-30 18:32 UTC, a-kotova commented on cypress/integration/tests/20_2_test.js
> +            cy.log("WHEN user changes product's quantity" )
Убрала лишние проверки. Оставила только проверку названия товара и цены товара (так как этого требует условие задания)

2020-11-30 18:33 UTC, a-kotova commented on cypress/integration/tests/20_2_test.js
> +                Cart.getItemByUrl(product.url).should('exist')
Добавила should чтобы при переходе напрямую в корзину два товара отображались корректно

2020-11-30 18:33 UTC, a-kotova commented on cypress/integration/tests/20_2_test.js
> +            this.products.forEach((product, index) => {
Сделала по-другому

2020-12-01 13:12 UTC, a-kotova commented on cypress.json
> +    "cartReloadTimeout": 5000
Исправила.

2020-12-01 13:41 UTC, s34rching requested changes
Падает

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/19408007/100748140-02fb6a00-33f4-11eb-988c-92ac96a3114d.png">

2020-12-01 13:41 UTC, s34rching commented on cypress/integration/tests/20_2_test.js
> +            cy.get('@products').then((products) => {
ван лав

2020-12-01 13:41 UTC, s34rching commented on cypress/integration/page-objects/GoogleCart.js
> +                cy.contains(this.countTotalPrice(array)).should('be.visible')
так выходит, что `getTotalPrice` немного лишний здесь, потому что ты проверила уже, что тотал корректный

2020-12-01 13:41 UTC, s34rching commented on cypress/integration/page-objects/GoogleCart.js
> +                cy.contains(this.countTotalPrice(array)).should('be.visible')
возможно, тебе надо сделать эту строку отдельным методом, если ты хочешь переиспользовать

2020-12-01 13:41 UTC, s34rching commented on cypress/integration/page-objects/GoogleCart.js
> +    increaseProductsQuantity (array) {
Переделать обязательно ВЕЗДЕ!
Параметры функции должны показывать что передается, трудно понять / читать.

array чего? bananas, boots, products...

2020-12-01 13:41 UTC, s34rching commented on debug.log
> +[1130/181911.393:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
удалить из гитхаба весь файл

2020-12-01 13:41 UTC, s34rching commented on debug.log
> +[1130/181911.393:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
делается через коммит

2020-12-01 13:41 UTC, s34rching commented on cypress/integration/page-objects/GoogleCart.js
> +                cy.contains(this.countTotalPrice(array)).should('be.visible')
как "на сейчас" - ок

2020-12-01 14:01 UTC, a-kotova commented on debug.log
> +[1130/181911.393:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Удалила

2020-12-01 14:06 UTC, a-kotova commented on cypress/integration/page-objects/GoogleCart.js
> +    increaseProductsQuantity (array) {
Исправила

2020-12-02 11:35 UTC, s34rching approved these changes
good to go

2020-12-02 11:35 UTC, s34rching commented on .gitignore
>  .idea/vcs.xml
лучше всю папку эту добавлять

2020-12-02 11:35 UTC, s34rching commented on cypress/integration/tests/20_2_test.js
> +                    Cart.productPrice.eq(index).should(($value) => {
`then`

2020-12-02 11:35 UTC, s34rching commented on cypress/integration/tests/20_2_test.js
> +                    Cart.productName.eq(index).should('have.text', `${products[index].title}`)
методы берущие со cтраницы что-нибудь лучше обозвать `getChtotoTam`

2020-12-02 11:35 UTC, s34rching commented on cypress/integration/tests/20_2_test.js
> +                cy.log('AND each added product is correct')
логеры лучше непосредственно перед шагом

2020-12-02 11:35 UTC, s34rching commented on cypress/integration/page-objects/GoogleCart.js
> +    increaseProductsQuantity (products_array) {
`products_array` - с underscore синтаксис Ruby
`productsArray` - Javascript

2020-12-02 11:35 UTC, s34rching commented on cypress/integration/page-objects/GoogleCart.js
> +    countTotalPrice (products_array) {
не обязательно добавлять `array`, `products` во множественном числе указывает на коллекцию и первое, что приходит на ум, что это должен быть `Array`

2020-12-02 13:07 UTC, merged